filebeat.inputs:
- type: filestream
  enabled: true
  id: app-logs
  paths:
    - /var/log/app/*.log
  fields:
    log_source: filebeat
  fields_under_root: true

# Kafka output
output.kafka:
  hosts: ["kafka:9092"]
  topic: "filebeat-logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

# Logging
logging.level: info
logging.to_files: false
logging.to_syslog: false

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
