filebeat.inputs:
- type: filestream
  enabled: true
  id: app-logs
  paths:
    - /var/log/app/*.log
  fields:
    log_source: filebeat
  fields_under_root: true

# Logstash output
output.logstash:
  hosts: ["logstash:5044"]

# Logging
logging.level: info
logging.to_files: false
logging.to_syslog: false

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
