filebeat.inputs:
- type: filestream
  enabled: true
  id: app-logs
  paths:
    - /var/log/app/*.log
  fields:
    log_source: filebeat
  fields_under_root: true

# Elasticsearch output
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-app-logs-%{+yyyy.MM.dd}"

# Disable all setup features - we don't need templates or ILM for basic logging
setup.ilm.enabled: false
setup.template.enabled: false
setup.dashboards.enabled: false

# Logging
logging.level: info
logging.to_files: false
logging.to_syslog: false

# Processors - decode JSON from message field
processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
